version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Slottet123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - slottet-sql-data:/var/opt/mssql

volumes:
  slottet-sql-data: